# Site settings
title: 暨南大学魔方协会官方网站
email: your-email@domain.com
description: "暨南大学魔方协会官方网站。\n使用 Jekyll 模板构建。"
baseurl: ""
url: "http://JNURubik.github.io"
github_username:  JNURubik

# Build settings
markdown: kramdown
permalink: pretty
